package mystical.cup.dao.mapper;

import java.util.List;
import mystical.cup.model.database.HttpConsumerDateMode;
import mystical.cup.model.database.HttpConsumerDateExample;
import org.apache.ibatis.annotations.Param;

public interface HttpConsumerDateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer_date
     *
     * @mbggenerated
     */
    int countByExample(HttpConsumerDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer_date
     *
     * @mbggenerated
     */
    int deleteByExample(HttpConsumerDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer_date
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer_date
     *
     * @mbggenerated
     */
    int insert(HttpConsumerDateMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer_date
     *
     * @mbggenerated
     */
    int insertSelective(HttpConsumerDateMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer_date
     *
     * @mbggenerated
     */
    List<HttpConsumerDateMode> selectByExample(HttpConsumerDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer_date
     *
     * @mbggenerated
     */
    HttpConsumerDateMode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer_date
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HttpConsumerDateMode record, @Param("example") HttpConsumerDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer_date
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HttpConsumerDateMode record, @Param("example") HttpConsumerDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer_date
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HttpConsumerDateMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer_date
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HttpConsumerDateMode record);
}