package mystical.cup.dao.mapper;

import java.util.List;

import mystical.cup.model.database.HttpConsumerMode;
import mystical.cup.model.database.HttpConsumerExample;
import org.apache.ibatis.annotations.Param;

public interface HttpConsumerMapper {
    List<HttpConsumerMode> selectLimit(@Param("begin") int begin, @Param("end") int end);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer
     *
     * @mbggenerated
     */
    int countByExample(HttpConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer
     *
     * @mbggenerated
     */
    int deleteByExample(HttpConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer
     *
     * @mbggenerated
     */
    int insert(HttpConsumerMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer
     *
     * @mbggenerated
     */
    int insertSelective(HttpConsumerMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer
     *
     * @mbggenerated
     */
    List<HttpConsumerMode> selectByExample(HttpConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer
     *
     * @mbggenerated
     */
    HttpConsumerMode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HttpConsumerMode record, @Param("example") HttpConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HttpConsumerMode record, @Param("example") HttpConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HttpConsumerMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_consumer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HttpConsumerMode record);
}