package mystical.cup.dao.mapper;

import java.util.List;
import mystical.cup.model.database.HttpProducerDataMode;
import mystical.cup.model.database.HttpProducerDataExample;
import org.apache.ibatis.annotations.Param;

public interface HttpProducerDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer_data
     *
     * @mbggenerated
     */
    int countByExample(HttpProducerDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer_data
     *
     * @mbggenerated
     */
    int deleteByExample(HttpProducerDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer_data
     *
     * @mbggenerated
     */
    int insert(HttpProducerDataMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer_data
     *
     * @mbggenerated
     */
    int insertSelective(HttpProducerDataMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer_data
     *
     * @mbggenerated
     */
    List<HttpProducerDataMode> selectByExample(HttpProducerDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer_data
     *
     * @mbggenerated
     */
    HttpProducerDataMode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer_data
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HttpProducerDataMode record, @Param("example") HttpProducerDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer_data
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HttpProducerDataMode record, @Param("example") HttpProducerDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HttpProducerDataMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HttpProducerDataMode record);
}