package mystical.cup.dao.mapper;

import java.util.List;
import mystical.cup.model.database.HttpStatisticsMode;
import mystical.cup.model.database.HttpStatisticsExample;
import org.apache.ibatis.annotations.Param;

public interface HttpStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_statistics
     *
     * @mbggenerated
     */
    int countByExample(HttpStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_statistics
     *
     * @mbggenerated
     */
    int deleteByExample(HttpStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_statistics
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_statistics
     *
     * @mbggenerated
     */
    int insert(HttpStatisticsMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_statistics
     *
     * @mbggenerated
     */
    int insertSelective(HttpStatisticsMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_statistics
     *
     * @mbggenerated
     */
    List<HttpStatisticsMode> selectByExample(HttpStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_statistics
     *
     * @mbggenerated
     */
    HttpStatisticsMode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_statistics
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HttpStatisticsMode record, @Param("example") HttpStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_statistics
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HttpStatisticsMode record, @Param("example") HttpStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_statistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HttpStatisticsMode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_statistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HttpStatisticsMode record);
}