package mystical.cup.dao.mapper;

import java.util.List;
import mystical.cup.model.database.HttpCatch;
import mystical.cup.model.database.HttpCatchExample;
import org.apache.ibatis.annotations.Param;

public interface HttpCatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_catch
     *
     * @mbggenerated
     */
    int countByExample(HttpCatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_catch
     *
     * @mbggenerated
     */
    int deleteByExample(HttpCatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_catch
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_catch
     *
     * @mbggenerated
     */
    int insert(HttpCatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_catch
     *
     * @mbggenerated
     */
    int insertSelective(HttpCatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_catch
     *
     * @mbggenerated
     */
    List<HttpCatch> selectByExample(HttpCatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_catch
     *
     * @mbggenerated
     */
    HttpCatch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_catch
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HttpCatch record, @Param("example") HttpCatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_catch
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HttpCatch record, @Param("example") HttpCatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_catch
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HttpCatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_catch
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HttpCatch record);
}