package mystical.cup.dao.mapper;

import java.util.List;
import mystical.cup.model.database.HttpListen;
import mystical.cup.model.database.HttpListenExample;
import org.apache.ibatis.annotations.Param;

public interface HttpListenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_listen
     *
     * @mbggenerated
     */
    int countByExample(HttpListenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_listen
     *
     * @mbggenerated
     */
    int deleteByExample(HttpListenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_listen
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_listen
     *
     * @mbggenerated
     */
    int insert(HttpListen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_listen
     *
     * @mbggenerated
     */
    int insertSelective(HttpListen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_listen
     *
     * @mbggenerated
     */
    List<HttpListen> selectByExample(HttpListenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_listen
     *
     * @mbggenerated
     */
    HttpListen selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_listen
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HttpListen record, @Param("example") HttpListenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_listen
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HttpListen record, @Param("example") HttpListenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_listen
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HttpListen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_listen
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HttpListen record);
}