package mystical.cup.dao.mapper;

import java.util.List;
import mystical.cup.model.database.RequestStatistics;
import mystical.cup.model.database.RequestStatisticsExample;
import org.apache.ibatis.annotations.Param;

public interface RequestStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_statistics
     *
     * @mbggenerated
     */
    int countByExample(RequestStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_statistics
     *
     * @mbggenerated
     */
    int deleteByExample(RequestStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_statistics
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_statistics
     *
     * @mbggenerated
     */
    int insert(RequestStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_statistics
     *
     * @mbggenerated
     */
    int insertSelective(RequestStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_statistics
     *
     * @mbggenerated
     */
    List<RequestStatistics> selectByExample(RequestStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_statistics
     *
     * @mbggenerated
     */
    RequestStatistics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_statistics
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RequestStatistics record, @Param("example") RequestStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_statistics
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RequestStatistics record, @Param("example") RequestStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_statistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RequestStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_statistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RequestStatistics record);
}