package mystical.cup.dao.mapper;

import java.util.List;
import mystical.cup.model.database.RequestJob;
import mystical.cup.model.database.RequestJobExample;
import org.apache.ibatis.annotations.Param;

public interface RequestJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_job
     *
     * @mbggenerated
     */
    int countByExample(RequestJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_job
     *
     * @mbggenerated
     */
    int deleteByExample(RequestJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_job
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_job
     *
     * @mbggenerated
     */
    int insert(RequestJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_job
     *
     * @mbggenerated
     */
    int insertSelective(RequestJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_job
     *
     * @mbggenerated
     */
    List<RequestJob> selectByExample(RequestJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_job
     *
     * @mbggenerated
     */
    RequestJob selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_job
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RequestJob record, @Param("example") RequestJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_job
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RequestJob record, @Param("example") RequestJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_job
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RequestJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_job
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RequestJob record);
}