package mystical.cup.dao.mapper;

import java.util.List;
import mystical.cup.model.database.RquestError;
import mystical.cup.model.database.RquestErrorExample;
import org.apache.ibatis.annotations.Param;

public interface RquestErrorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_error
     *
     * @mbggenerated
     */
    int countByExample(RquestErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_error
     *
     * @mbggenerated
     */
    int deleteByExample(RquestErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_error
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_error
     *
     * @mbggenerated
     */
    int insert(RquestError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_error
     *
     * @mbggenerated
     */
    int insertSelective(RquestError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_error
     *
     * @mbggenerated
     */
    List<RquestError> selectByExample(RquestErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_error
     *
     * @mbggenerated
     */
    RquestError selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_error
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RquestError record, @Param("example") RquestErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_error
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RquestError record, @Param("example") RquestErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_error
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RquestError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_error
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RquestError record);
}