package mystical.cup.model.database;

public class ConfigController {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.controller_url
     *
     * @mbggenerated
     */
    private String controllerUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.param_switch
     *
     * @mbggenerated
     */
    private String paramSwitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.task_name
     *
     * @mbggenerated
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.subject
     *
     * @mbggenerated
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.sub_subject
     *
     * @mbggenerated
     */
    private String subSubject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.workflow_name
     *
     * @mbggenerated
     */
    private String workflowName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.error_item_type
     *
     * @mbggenerated
     */
    private String errorItemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.error_decription
     *
     * @mbggenerated
     */
    private String errorDecription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.is_token
     *
     * @mbggenerated
     */
    private Integer isToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.is_valid
     *
     * @mbggenerated
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.decription
     *
     * @mbggenerated
     */
    private String decription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.id
     *
     * @return the value of config_controller.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.id
     *
     * @param id the value for config_controller.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.create_time
     *
     * @return the value of config_controller.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.create_time
     *
     * @param createTime the value for config_controller.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.update_time
     *
     * @return the value of config_controller.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.update_time
     *
     * @param updateTime the value for config_controller.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.controller_url
     *
     * @return the value of config_controller.controller_url
     *
     * @mbggenerated
     */
    public String getControllerUrl() {
        return controllerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.controller_url
     *
     * @param controllerUrl the value for config_controller.controller_url
     *
     * @mbggenerated
     */
    public void setControllerUrl(String controllerUrl) {
        this.controllerUrl = controllerUrl == null ? null : controllerUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.param_switch
     *
     * @return the value of config_controller.param_switch
     *
     * @mbggenerated
     */
    public String getParamSwitch() {
        return paramSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.param_switch
     *
     * @param paramSwitch the value for config_controller.param_switch
     *
     * @mbggenerated
     */
    public void setParamSwitch(String paramSwitch) {
        this.paramSwitch = paramSwitch == null ? null : paramSwitch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.task_name
     *
     * @return the value of config_controller.task_name
     *
     * @mbggenerated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.task_name
     *
     * @param taskName the value for config_controller.task_name
     *
     * @mbggenerated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.subject
     *
     * @return the value of config_controller.subject
     *
     * @mbggenerated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.subject
     *
     * @param subject the value for config_controller.subject
     *
     * @mbggenerated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.sub_subject
     *
     * @return the value of config_controller.sub_subject
     *
     * @mbggenerated
     */
    public String getSubSubject() {
        return subSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.sub_subject
     *
     * @param subSubject the value for config_controller.sub_subject
     *
     * @mbggenerated
     */
    public void setSubSubject(String subSubject) {
        this.subSubject = subSubject == null ? null : subSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.workflow_name
     *
     * @return the value of config_controller.workflow_name
     *
     * @mbggenerated
     */
    public String getWorkflowName() {
        return workflowName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.workflow_name
     *
     * @param workflowName the value for config_controller.workflow_name
     *
     * @mbggenerated
     */
    public void setWorkflowName(String workflowName) {
        this.workflowName = workflowName == null ? null : workflowName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.error_item_type
     *
     * @return the value of config_controller.error_item_type
     *
     * @mbggenerated
     */
    public String getErrorItemType() {
        return errorItemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.error_item_type
     *
     * @param errorItemType the value for config_controller.error_item_type
     *
     * @mbggenerated
     */
    public void setErrorItemType(String errorItemType) {
        this.errorItemType = errorItemType == null ? null : errorItemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.error_decription
     *
     * @return the value of config_controller.error_decription
     *
     * @mbggenerated
     */
    public String getErrorDecription() {
        return errorDecription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.error_decription
     *
     * @param errorDecription the value for config_controller.error_decription
     *
     * @mbggenerated
     */
    public void setErrorDecription(String errorDecription) {
        this.errorDecription = errorDecription == null ? null : errorDecription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.is_token
     *
     * @return the value of config_controller.is_token
     *
     * @mbggenerated
     */
    public Integer getIsToken() {
        return isToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.is_token
     *
     * @param isToken the value for config_controller.is_token
     *
     * @mbggenerated
     */
    public void setIsToken(Integer isToken) {
        this.isToken = isToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.is_valid
     *
     * @return the value of config_controller.is_valid
     *
     * @mbggenerated
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.is_valid
     *
     * @param isValid the value for config_controller.is_valid
     *
     * @mbggenerated
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.decription
     *
     * @return the value of config_controller.decription
     *
     * @mbggenerated
     */
    public String getDecription() {
        return decription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.decription
     *
     * @param decription the value for config_controller.decription
     *
     * @mbggenerated
     */
    public void setDecription(String decription) {
        this.decription = decription == null ? null : decription.trim();
    }
}