package mystical.cup.model.database;

import java.util.ArrayList;
import java.util.List;

public class ConfigControllerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config_controller
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config_controller
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config_controller
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_controller
     *
     * @mbggenerated
     */
    public ConfigControllerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_controller
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_controller
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_controller
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_controller
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_controller
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_controller
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_controller
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_controller
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_controller
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_controller
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config_controller
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Integer value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Integer value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Integer value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Integer value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Integer> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Integer> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Integer value1, Integer value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Integer value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Integer value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Integer value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Integer value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Integer> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Integer> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Integer value1, Integer value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andControllerUrlIsNull() {
            addCriterion("controller_url is null");
            return (Criteria) this;
        }

        public Criteria andControllerUrlIsNotNull() {
            addCriterion("controller_url is not null");
            return (Criteria) this;
        }

        public Criteria andControllerUrlEqualTo(String value) {
            addCriterion("controller_url =", value, "controllerUrl");
            return (Criteria) this;
        }

        public Criteria andControllerUrlNotEqualTo(String value) {
            addCriterion("controller_url <>", value, "controllerUrl");
            return (Criteria) this;
        }

        public Criteria andControllerUrlGreaterThan(String value) {
            addCriterion("controller_url >", value, "controllerUrl");
            return (Criteria) this;
        }

        public Criteria andControllerUrlGreaterThanOrEqualTo(String value) {
            addCriterion("controller_url >=", value, "controllerUrl");
            return (Criteria) this;
        }

        public Criteria andControllerUrlLessThan(String value) {
            addCriterion("controller_url <", value, "controllerUrl");
            return (Criteria) this;
        }

        public Criteria andControllerUrlLessThanOrEqualTo(String value) {
            addCriterion("controller_url <=", value, "controllerUrl");
            return (Criteria) this;
        }

        public Criteria andControllerUrlLike(String value) {
            addCriterion("controller_url like", value, "controllerUrl");
            return (Criteria) this;
        }

        public Criteria andControllerUrlNotLike(String value) {
            addCriterion("controller_url not like", value, "controllerUrl");
            return (Criteria) this;
        }

        public Criteria andControllerUrlIn(List<String> values) {
            addCriterion("controller_url in", values, "controllerUrl");
            return (Criteria) this;
        }

        public Criteria andControllerUrlNotIn(List<String> values) {
            addCriterion("controller_url not in", values, "controllerUrl");
            return (Criteria) this;
        }

        public Criteria andControllerUrlBetween(String value1, String value2) {
            addCriterion("controller_url between", value1, value2, "controllerUrl");
            return (Criteria) this;
        }

        public Criteria andControllerUrlNotBetween(String value1, String value2) {
            addCriterion("controller_url not between", value1, value2, "controllerUrl");
            return (Criteria) this;
        }

        public Criteria andParamSwitchIsNull() {
            addCriterion("param_switch is null");
            return (Criteria) this;
        }

        public Criteria andParamSwitchIsNotNull() {
            addCriterion("param_switch is not null");
            return (Criteria) this;
        }

        public Criteria andParamSwitchEqualTo(String value) {
            addCriterion("param_switch =", value, "paramSwitch");
            return (Criteria) this;
        }

        public Criteria andParamSwitchNotEqualTo(String value) {
            addCriterion("param_switch <>", value, "paramSwitch");
            return (Criteria) this;
        }

        public Criteria andParamSwitchGreaterThan(String value) {
            addCriterion("param_switch >", value, "paramSwitch");
            return (Criteria) this;
        }

        public Criteria andParamSwitchGreaterThanOrEqualTo(String value) {
            addCriterion("param_switch >=", value, "paramSwitch");
            return (Criteria) this;
        }

        public Criteria andParamSwitchLessThan(String value) {
            addCriterion("param_switch <", value, "paramSwitch");
            return (Criteria) this;
        }

        public Criteria andParamSwitchLessThanOrEqualTo(String value) {
            addCriterion("param_switch <=", value, "paramSwitch");
            return (Criteria) this;
        }

        public Criteria andParamSwitchLike(String value) {
            addCriterion("param_switch like", value, "paramSwitch");
            return (Criteria) this;
        }

        public Criteria andParamSwitchNotLike(String value) {
            addCriterion("param_switch not like", value, "paramSwitch");
            return (Criteria) this;
        }

        public Criteria andParamSwitchIn(List<String> values) {
            addCriterion("param_switch in", values, "paramSwitch");
            return (Criteria) this;
        }

        public Criteria andParamSwitchNotIn(List<String> values) {
            addCriterion("param_switch not in", values, "paramSwitch");
            return (Criteria) this;
        }

        public Criteria andParamSwitchBetween(String value1, String value2) {
            addCriterion("param_switch between", value1, value2, "paramSwitch");
            return (Criteria) this;
        }

        public Criteria andParamSwitchNotBetween(String value1, String value2) {
            addCriterion("param_switch not between", value1, value2, "paramSwitch");
            return (Criteria) this;
        }

        public Criteria andTaskNameIsNull() {
            addCriterion("task_name is null");
            return (Criteria) this;
        }

        public Criteria andTaskNameIsNotNull() {
            addCriterion("task_name is not null");
            return (Criteria) this;
        }

        public Criteria andTaskNameEqualTo(String value) {
            addCriterion("task_name =", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotEqualTo(String value) {
            addCriterion("task_name <>", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameGreaterThan(String value) {
            addCriterion("task_name >", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameGreaterThanOrEqualTo(String value) {
            addCriterion("task_name >=", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameLessThan(String value) {
            addCriterion("task_name <", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameLessThanOrEqualTo(String value) {
            addCriterion("task_name <=", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameLike(String value) {
            addCriterion("task_name like", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotLike(String value) {
            addCriterion("task_name not like", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameIn(List<String> values) {
            addCriterion("task_name in", values, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotIn(List<String> values) {
            addCriterion("task_name not in", values, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameBetween(String value1, String value2) {
            addCriterion("task_name between", value1, value2, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotBetween(String value1, String value2) {
            addCriterion("task_name not between", value1, value2, "taskName");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNull() {
            addCriterion("subject is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNotNull() {
            addCriterion("subject is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectEqualTo(String value) {
            addCriterion("subject =", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotEqualTo(String value) {
            addCriterion("subject <>", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThan(String value) {
            addCriterion("subject >", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("subject >=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThan(String value) {
            addCriterion("subject <", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThanOrEqualTo(String value) {
            addCriterion("subject <=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLike(String value) {
            addCriterion("subject like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotLike(String value) {
            addCriterion("subject not like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectIn(List<String> values) {
            addCriterion("subject in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotIn(List<String> values) {
            addCriterion("subject not in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectBetween(String value1, String value2) {
            addCriterion("subject between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotBetween(String value1, String value2) {
            addCriterion("subject not between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectIsNull() {
            addCriterion("sub_subject is null");
            return (Criteria) this;
        }

        public Criteria andSubSubjectIsNotNull() {
            addCriterion("sub_subject is not null");
            return (Criteria) this;
        }

        public Criteria andSubSubjectEqualTo(String value) {
            addCriterion("sub_subject =", value, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectNotEqualTo(String value) {
            addCriterion("sub_subject <>", value, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectGreaterThan(String value) {
            addCriterion("sub_subject >", value, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("sub_subject >=", value, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectLessThan(String value) {
            addCriterion("sub_subject <", value, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectLessThanOrEqualTo(String value) {
            addCriterion("sub_subject <=", value, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectLike(String value) {
            addCriterion("sub_subject like", value, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectNotLike(String value) {
            addCriterion("sub_subject not like", value, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectIn(List<String> values) {
            addCriterion("sub_subject in", values, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectNotIn(List<String> values) {
            addCriterion("sub_subject not in", values, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectBetween(String value1, String value2) {
            addCriterion("sub_subject between", value1, value2, "subSubject");
            return (Criteria) this;
        }

        public Criteria andSubSubjectNotBetween(String value1, String value2) {
            addCriterion("sub_subject not between", value1, value2, "subSubject");
            return (Criteria) this;
        }

        public Criteria andWorkflowNameIsNull() {
            addCriterion("workflow_name is null");
            return (Criteria) this;
        }

        public Criteria andWorkflowNameIsNotNull() {
            addCriterion("workflow_name is not null");
            return (Criteria) this;
        }

        public Criteria andWorkflowNameEqualTo(String value) {
            addCriterion("workflow_name =", value, "workflowName");
            return (Criteria) this;
        }

        public Criteria andWorkflowNameNotEqualTo(String value) {
            addCriterion("workflow_name <>", value, "workflowName");
            return (Criteria) this;
        }

        public Criteria andWorkflowNameGreaterThan(String value) {
            addCriterion("workflow_name >", value, "workflowName");
            return (Criteria) this;
        }

        public Criteria andWorkflowNameGreaterThanOrEqualTo(String value) {
            addCriterion("workflow_name >=", value, "workflowName");
            return (Criteria) this;
        }

        public Criteria andWorkflowNameLessThan(String value) {
            addCriterion("workflow_name <", value, "workflowName");
            return (Criteria) this;
        }

        public Criteria andWorkflowNameLessThanOrEqualTo(String value) {
            addCriterion("workflow_name <=", value, "workflowName");
            return (Criteria) this;
        }

        public Criteria andWorkflowNameLike(String value) {
            addCriterion("workflow_name like", value, "workflowName");
            return (Criteria) this;
        }

        public Criteria andWorkflowNameNotLike(String value) {
            addCriterion("workflow_name not like", value, "workflowName");
            return (Criteria) this;
        }

        public Criteria andWorkflowNameIn(List<String> values) {
            addCriterion("workflow_name in", values, "workflowName");
            return (Criteria) this;
        }

        public Criteria andWorkflowNameNotIn(List<String> values) {
            addCriterion("workflow_name not in", values, "workflowName");
            return (Criteria) this;
        }

        public Criteria andWorkflowNameBetween(String value1, String value2) {
            addCriterion("workflow_name between", value1, value2, "workflowName");
            return (Criteria) this;
        }

        public Criteria andWorkflowNameNotBetween(String value1, String value2) {
            addCriterion("workflow_name not between", value1, value2, "workflowName");
            return (Criteria) this;
        }

        public Criteria andErrorItemTypeIsNull() {
            addCriterion("error_item_type is null");
            return (Criteria) this;
        }

        public Criteria andErrorItemTypeIsNotNull() {
            addCriterion("error_item_type is not null");
            return (Criteria) this;
        }

        public Criteria andErrorItemTypeEqualTo(String value) {
            addCriterion("error_item_type =", value, "errorItemType");
            return (Criteria) this;
        }

        public Criteria andErrorItemTypeNotEqualTo(String value) {
            addCriterion("error_item_type <>", value, "errorItemType");
            return (Criteria) this;
        }

        public Criteria andErrorItemTypeGreaterThan(String value) {
            addCriterion("error_item_type >", value, "errorItemType");
            return (Criteria) this;
        }

        public Criteria andErrorItemTypeGreaterThanOrEqualTo(String value) {
            addCriterion("error_item_type >=", value, "errorItemType");
            return (Criteria) this;
        }

        public Criteria andErrorItemTypeLessThan(String value) {
            addCriterion("error_item_type <", value, "errorItemType");
            return (Criteria) this;
        }

        public Criteria andErrorItemTypeLessThanOrEqualTo(String value) {
            addCriterion("error_item_type <=", value, "errorItemType");
            return (Criteria) this;
        }

        public Criteria andErrorItemTypeLike(String value) {
            addCriterion("error_item_type like", value, "errorItemType");
            return (Criteria) this;
        }

        public Criteria andErrorItemTypeNotLike(String value) {
            addCriterion("error_item_type not like", value, "errorItemType");
            return (Criteria) this;
        }

        public Criteria andErrorItemTypeIn(List<String> values) {
            addCriterion("error_item_type in", values, "errorItemType");
            return (Criteria) this;
        }

        public Criteria andErrorItemTypeNotIn(List<String> values) {
            addCriterion("error_item_type not in", values, "errorItemType");
            return (Criteria) this;
        }

        public Criteria andErrorItemTypeBetween(String value1, String value2) {
            addCriterion("error_item_type between", value1, value2, "errorItemType");
            return (Criteria) this;
        }

        public Criteria andErrorItemTypeNotBetween(String value1, String value2) {
            addCriterion("error_item_type not between", value1, value2, "errorItemType");
            return (Criteria) this;
        }

        public Criteria andErrorDecriptionIsNull() {
            addCriterion("error_decription is null");
            return (Criteria) this;
        }

        public Criteria andErrorDecriptionIsNotNull() {
            addCriterion("error_decription is not null");
            return (Criteria) this;
        }

        public Criteria andErrorDecriptionEqualTo(String value) {
            addCriterion("error_decription =", value, "errorDecription");
            return (Criteria) this;
        }

        public Criteria andErrorDecriptionNotEqualTo(String value) {
            addCriterion("error_decription <>", value, "errorDecription");
            return (Criteria) this;
        }

        public Criteria andErrorDecriptionGreaterThan(String value) {
            addCriterion("error_decription >", value, "errorDecription");
            return (Criteria) this;
        }

        public Criteria andErrorDecriptionGreaterThanOrEqualTo(String value) {
            addCriterion("error_decription >=", value, "errorDecription");
            return (Criteria) this;
        }

        public Criteria andErrorDecriptionLessThan(String value) {
            addCriterion("error_decription <", value, "errorDecription");
            return (Criteria) this;
        }

        public Criteria andErrorDecriptionLessThanOrEqualTo(String value) {
            addCriterion("error_decription <=", value, "errorDecription");
            return (Criteria) this;
        }

        public Criteria andErrorDecriptionLike(String value) {
            addCriterion("error_decription like", value, "errorDecription");
            return (Criteria) this;
        }

        public Criteria andErrorDecriptionNotLike(String value) {
            addCriterion("error_decription not like", value, "errorDecription");
            return (Criteria) this;
        }

        public Criteria andErrorDecriptionIn(List<String> values) {
            addCriterion("error_decription in", values, "errorDecription");
            return (Criteria) this;
        }

        public Criteria andErrorDecriptionNotIn(List<String> values) {
            addCriterion("error_decription not in", values, "errorDecription");
            return (Criteria) this;
        }

        public Criteria andErrorDecriptionBetween(String value1, String value2) {
            addCriterion("error_decription between", value1, value2, "errorDecription");
            return (Criteria) this;
        }

        public Criteria andErrorDecriptionNotBetween(String value1, String value2) {
            addCriterion("error_decription not between", value1, value2, "errorDecription");
            return (Criteria) this;
        }

        public Criteria andIsTokenIsNull() {
            addCriterion("is_token is null");
            return (Criteria) this;
        }

        public Criteria andIsTokenIsNotNull() {
            addCriterion("is_token is not null");
            return (Criteria) this;
        }

        public Criteria andIsTokenEqualTo(Integer value) {
            addCriterion("is_token =", value, "isToken");
            return (Criteria) this;
        }

        public Criteria andIsTokenNotEqualTo(Integer value) {
            addCriterion("is_token <>", value, "isToken");
            return (Criteria) this;
        }

        public Criteria andIsTokenGreaterThan(Integer value) {
            addCriterion("is_token >", value, "isToken");
            return (Criteria) this;
        }

        public Criteria andIsTokenGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_token >=", value, "isToken");
            return (Criteria) this;
        }

        public Criteria andIsTokenLessThan(Integer value) {
            addCriterion("is_token <", value, "isToken");
            return (Criteria) this;
        }

        public Criteria andIsTokenLessThanOrEqualTo(Integer value) {
            addCriterion("is_token <=", value, "isToken");
            return (Criteria) this;
        }

        public Criteria andIsTokenIn(List<Integer> values) {
            addCriterion("is_token in", values, "isToken");
            return (Criteria) this;
        }

        public Criteria andIsTokenNotIn(List<Integer> values) {
            addCriterion("is_token not in", values, "isToken");
            return (Criteria) this;
        }

        public Criteria andIsTokenBetween(Integer value1, Integer value2) {
            addCriterion("is_token between", value1, value2, "isToken");
            return (Criteria) this;
        }

        public Criteria andIsTokenNotBetween(Integer value1, Integer value2) {
            addCriterion("is_token not between", value1, value2, "isToken");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNull() {
            addCriterion("is_valid is null");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNotNull() {
            addCriterion("is_valid is not null");
            return (Criteria) this;
        }

        public Criteria andIsValidEqualTo(Integer value) {
            addCriterion("is_valid =", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotEqualTo(Integer value) {
            addCriterion("is_valid <>", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThan(Integer value) {
            addCriterion("is_valid >", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_valid >=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThan(Integer value) {
            addCriterion("is_valid <", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThanOrEqualTo(Integer value) {
            addCriterion("is_valid <=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidIn(List<Integer> values) {
            addCriterion("is_valid in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotIn(List<Integer> values) {
            addCriterion("is_valid not in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidBetween(Integer value1, Integer value2) {
            addCriterion("is_valid between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotBetween(Integer value1, Integer value2) {
            addCriterion("is_valid not between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andDecriptionIsNull() {
            addCriterion("decription is null");
            return (Criteria) this;
        }

        public Criteria andDecriptionIsNotNull() {
            addCriterion("decription is not null");
            return (Criteria) this;
        }

        public Criteria andDecriptionEqualTo(String value) {
            addCriterion("decription =", value, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionNotEqualTo(String value) {
            addCriterion("decription <>", value, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionGreaterThan(String value) {
            addCriterion("decription >", value, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionGreaterThanOrEqualTo(String value) {
            addCriterion("decription >=", value, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionLessThan(String value) {
            addCriterion("decription <", value, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionLessThanOrEqualTo(String value) {
            addCriterion("decription <=", value, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionLike(String value) {
            addCriterion("decription like", value, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionNotLike(String value) {
            addCriterion("decription not like", value, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionIn(List<String> values) {
            addCriterion("decription in", values, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionNotIn(List<String> values) {
            addCriterion("decription not in", values, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionBetween(String value1, String value2) {
            addCriterion("decription between", value1, value2, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionNotBetween(String value1, String value2) {
            addCriterion("decription not between", value1, value2, "decription");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config_controller
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config_controller
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}