package mystical.cup.model.database;

public class ConfigController {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.controller_url
     *
     * @mbggenerated
     */
    private String controllerUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.output_param
     *
     * @mbggenerated
     */
    private String outputParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.input_param
     *
     * @mbggenerated
     */
    private String inputParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.is_valid
     *
     * @mbggenerated
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_controller.decription
     *
     * @mbggenerated
     */
    private String decription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.id
     *
     * @return the value of config_controller.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.id
     *
     * @param id the value for config_controller.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.create_time
     *
     * @return the value of config_controller.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.create_time
     *
     * @param createTime the value for config_controller.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.update_time
     *
     * @return the value of config_controller.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.update_time
     *
     * @param updateTime the value for config_controller.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.controller_url
     *
     * @return the value of config_controller.controller_url
     *
     * @mbggenerated
     */
    public String getControllerUrl() {
        return controllerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.controller_url
     *
     * @param controllerUrl the value for config_controller.controller_url
     *
     * @mbggenerated
     */
    public void setControllerUrl(String controllerUrl) {
        this.controllerUrl = controllerUrl == null ? null : controllerUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.output_param
     *
     * @return the value of config_controller.output_param
     *
     * @mbggenerated
     */
    public String getOutputParam() {
        return outputParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.output_param
     *
     * @param outputParam the value for config_controller.output_param
     *
     * @mbggenerated
     */
    public void setOutputParam(String outputParam) {
        this.outputParam = outputParam == null ? null : outputParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.input_param
     *
     * @return the value of config_controller.input_param
     *
     * @mbggenerated
     */
    public String getInputParam() {
        return inputParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.input_param
     *
     * @param inputParam the value for config_controller.input_param
     *
     * @mbggenerated
     */
    public void setInputParam(String inputParam) {
        this.inputParam = inputParam == null ? null : inputParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.is_valid
     *
     * @return the value of config_controller.is_valid
     *
     * @mbggenerated
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.is_valid
     *
     * @param isValid the value for config_controller.is_valid
     *
     * @mbggenerated
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.type
     *
     * @return the value of config_controller.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.type
     *
     * @param type the value for config_controller.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_controller.decription
     *
     * @return the value of config_controller.decription
     *
     * @mbggenerated
     */
    public String getDecription() {
        return decription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_controller.decription
     *
     * @param decription the value for config_controller.decription
     *
     * @mbggenerated
     */
    public void setDecription(String decription) {
        this.decription = decription == null ? null : decription.trim();
    }
}