package mystical.cup.model.database;

import java.util.Date;

public class HttpListen {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_listen.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_listen.request_gid
     *
     * @mbggenerated
     */
    private String requestGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_listen.request_body
     *
     * @mbggenerated
     */
    private String requestBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_listen.response_body
     *
     * @mbggenerated
     */
    private String responseBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_listen.reques_time
     *
     * @mbggenerated
     */
    private String requesTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_listen.response_time
     *
     * @mbggenerated
     */
    private String responseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_listen.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_listen.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_listen.request_type
     *
     * @mbggenerated
     */
    private String requestType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_listen.id
     *
     * @return the value of http_listen.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_listen.id
     *
     * @param id the value for http_listen.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_listen.request_gid
     *
     * @return the value of http_listen.request_gid
     *
     * @mbggenerated
     */
    public String getRequestGid() {
        return requestGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_listen.request_gid
     *
     * @param requestGid the value for http_listen.request_gid
     *
     * @mbggenerated
     */
    public void setRequestGid(String requestGid) {
        this.requestGid = requestGid == null ? null : requestGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_listen.request_body
     *
     * @return the value of http_listen.request_body
     *
     * @mbggenerated
     */
    public String getRequestBody() {
        return requestBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_listen.request_body
     *
     * @param requestBody the value for http_listen.request_body
     *
     * @mbggenerated
     */
    public void setRequestBody(String requestBody) {
        this.requestBody = requestBody == null ? null : requestBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_listen.response_body
     *
     * @return the value of http_listen.response_body
     *
     * @mbggenerated
     */
    public String getResponseBody() {
        return responseBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_listen.response_body
     *
     * @param responseBody the value for http_listen.response_body
     *
     * @mbggenerated
     */
    public void setResponseBody(String responseBody) {
        this.responseBody = responseBody == null ? null : responseBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_listen.reques_time
     *
     * @return the value of http_listen.reques_time
     *
     * @mbggenerated
     */
    public String getRequesTime() {
        return requesTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_listen.reques_time
     *
     * @param requesTime the value for http_listen.reques_time
     *
     * @mbggenerated
     */
    public void setRequesTime(String requesTime) {
        this.requesTime = requesTime == null ? null : requesTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_listen.response_time
     *
     * @return the value of http_listen.response_time
     *
     * @mbggenerated
     */
    public String getResponseTime() {
        return responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_listen.response_time
     *
     * @param responseTime the value for http_listen.response_time
     *
     * @mbggenerated
     */
    public void setResponseTime(String responseTime) {
        this.responseTime = responseTime == null ? null : responseTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_listen.create_time
     *
     * @return the value of http_listen.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_listen.create_time
     *
     * @param createTime the value for http_listen.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_listen.update_time
     *
     * @return the value of http_listen.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_listen.update_time
     *
     * @param updateTime the value for http_listen.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_listen.request_type
     *
     * @return the value of http_listen.request_type
     *
     * @mbggenerated
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_listen.request_type
     *
     * @param requestType the value for http_listen.request_type
     *
     * @mbggenerated
     */
    public void setRequestType(String requestType) {
        this.requestType = requestType == null ? null : requestType.trim();
    }
}