package mystical.cup.model.database;

import java.util.Date;

public class HttpStatisticsMode{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_statistics.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_statistics.req_param
     *
     * @mbggenerated
     */
    private String reqParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_statistics.resp_param
     *
     * @mbggenerated
     */
    private String respParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_statistics.request_time
     *
     * @mbggenerated
     */
    private String requestTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_statistics.response_time
     *
     * @mbggenerated
     */
    private String responseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_statistics.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_statistics.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_statistics.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_statistics.id
     *
     * @return the value of http_statistics.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_statistics.id
     *
     * @param id the value for http_statistics.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_statistics.req_param
     *
     * @return the value of http_statistics.req_param
     *
     * @mbggenerated
     */
    public String getReqParam() {
        return reqParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_statistics.req_param
     *
     * @param reqParam the value for http_statistics.req_param
     *
     * @mbggenerated
     */
    public void setReqParam(String reqParam) {
        this.reqParam = reqParam == null ? null : reqParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_statistics.resp_param
     *
     * @return the value of http_statistics.resp_param
     *
     * @mbggenerated
     */
    public String getRespParam() {
        return respParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_statistics.resp_param
     *
     * @param respParam the value for http_statistics.resp_param
     *
     * @mbggenerated
     */
    public void setRespParam(String respParam) {
        this.respParam = respParam == null ? null : respParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_statistics.request_time
     *
     * @return the value of http_statistics.request_time
     *
     * @mbggenerated
     */
    public String getRequestTime() {
        return requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_statistics.request_time
     *
     * @param requestTime the value for http_statistics.request_time
     *
     * @mbggenerated
     */
    public void setRequestTime(String requestTime) {
        this.requestTime = requestTime == null ? null : requestTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_statistics.response_time
     *
     * @return the value of http_statistics.response_time
     *
     * @mbggenerated
     */
    public String getResponseTime() {
        return responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_statistics.response_time
     *
     * @param responseTime the value for http_statistics.response_time
     *
     * @mbggenerated
     */
    public void setResponseTime(String responseTime) {
        this.responseTime = responseTime == null ? null : responseTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_statistics.status
     *
     * @return the value of http_statistics.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_statistics.status
     *
     * @param status the value for http_statistics.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_statistics.create_time
     *
     * @return the value of http_statistics.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_statistics.create_time
     *
     * @param createTime the value for http_statistics.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_statistics.update_time
     *
     * @return the value of http_statistics.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_statistics.update_time
     *
     * @param updateTime the value for http_statistics.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}