package mystical.cup.model.database;

import java.util.Date;

public class HttpProducerMode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_producer.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_producer.req_url
     *
     * @mbggenerated
     */
    private String reqUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_producer.req_para_config
     *
     * @mbggenerated
     */
    private String reqParaConfig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_producer.req_success_code
     *
     * @mbggenerated
     */
    private String reqSuccessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_producer.req_type
     *
     * @mbggenerated
     */
    private String reqType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_producer.req_begin_time
     *
     * @mbggenerated
     */
    private Date reqBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_producer.req_end_time
     *
     * @mbggenerated
     */
    private Date reqEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_producer.req_step_time
     *
     * @mbggenerated
     */
    private String reqStepTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_producer.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_producer.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_producer.statistics
     *
     * @mbggenerated
     */
    private Boolean statistics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_producer.ak
     *
     * @mbggenerated
     */
    private String ak;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_producer.sk
     *
     * @mbggenerated
     */
    private String sk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_producer.aksk_check
     *
     * @mbggenerated
     */
    private Boolean akskCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_producer.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_producer.id
     *
     * @return the value of http_producer.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_producer.id
     *
     * @param id the value for http_producer.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_producer.req_url
     *
     * @return the value of http_producer.req_url
     *
     * @mbggenerated
     */
    public String getReqUrl() {
        return reqUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_producer.req_url
     *
     * @param reqUrl the value for http_producer.req_url
     *
     * @mbggenerated
     */
    public void setReqUrl(String reqUrl) {
        this.reqUrl = reqUrl == null ? null : reqUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_producer.req_para_config
     *
     * @return the value of http_producer.req_para_config
     *
     * @mbggenerated
     */
    public String getReqParaConfig() {
        return reqParaConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_producer.req_para_config
     *
     * @param reqParaConfig the value for http_producer.req_para_config
     *
     * @mbggenerated
     */
    public void setReqParaConfig(String reqParaConfig) {
        this.reqParaConfig = reqParaConfig == null ? null : reqParaConfig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_producer.req_success_code
     *
     * @return the value of http_producer.req_success_code
     *
     * @mbggenerated
     */
    public String getReqSuccessCode() {
        return reqSuccessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_producer.req_success_code
     *
     * @param reqSuccessCode the value for http_producer.req_success_code
     *
     * @mbggenerated
     */
    public void setReqSuccessCode(String reqSuccessCode) {
        this.reqSuccessCode = reqSuccessCode == null ? null : reqSuccessCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_producer.req_type
     *
     * @return the value of http_producer.req_type
     *
     * @mbggenerated
     */
    public String getReqType() {
        return reqType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_producer.req_type
     *
     * @param reqType the value for http_producer.req_type
     *
     * @mbggenerated
     */
    public void setReqType(String reqType) {
        this.reqType = reqType == null ? null : reqType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_producer.req_begin_time
     *
     * @return the value of http_producer.req_begin_time
     *
     * @mbggenerated
     */
    public Date getReqBeginTime() {
        return reqBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_producer.req_begin_time
     *
     * @param reqBeginTime the value for http_producer.req_begin_time
     *
     * @mbggenerated
     */
    public void setReqBeginTime(Date reqBeginTime) {
        this.reqBeginTime = reqBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_producer.req_end_time
     *
     * @return the value of http_producer.req_end_time
     *
     * @mbggenerated
     */
    public Date getReqEndTime() {
        return reqEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_producer.req_end_time
     *
     * @param reqEndTime the value for http_producer.req_end_time
     *
     * @mbggenerated
     */
    public void setReqEndTime(Date reqEndTime) {
        this.reqEndTime = reqEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_producer.req_step_time
     *
     * @return the value of http_producer.req_step_time
     *
     * @mbggenerated
     */
    public String getReqStepTime() {
        return reqStepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_producer.req_step_time
     *
     * @param reqStepTime the value for http_producer.req_step_time
     *
     * @mbggenerated
     */
    public void setReqStepTime(String reqStepTime) {
        this.reqStepTime = reqStepTime == null ? null : reqStepTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_producer.create_time
     *
     * @return the value of http_producer.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_producer.create_time
     *
     * @param createTime the value for http_producer.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_producer.update_time
     *
     * @return the value of http_producer.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_producer.update_time
     *
     * @param updateTime the value for http_producer.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_producer.statistics
     *
     * @return the value of http_producer.statistics
     *
     * @mbggenerated
     */
    public Boolean getStatistics() {
        return statistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_producer.statistics
     *
     * @param statistics the value for http_producer.statistics
     *
     * @mbggenerated
     */
    public void setStatistics(Boolean statistics) {
        this.statistics = statistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_producer.ak
     *
     * @return the value of http_producer.ak
     *
     * @mbggenerated
     */
    public String getAk() {
        return ak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_producer.ak
     *
     * @param ak the value for http_producer.ak
     *
     * @mbggenerated
     */
    public void setAk(String ak) {
        this.ak = ak == null ? null : ak.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_producer.sk
     *
     * @return the value of http_producer.sk
     *
     * @mbggenerated
     */
    public String getSk() {
        return sk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_producer.sk
     *
     * @param sk the value for http_producer.sk
     *
     * @mbggenerated
     */
    public void setSk(String sk) {
        this.sk = sk == null ? null : sk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_producer.aksk_check
     *
     * @return the value of http_producer.aksk_check
     *
     * @mbggenerated
     */
    public Boolean getAkskCheck() {
        return akskCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_producer.aksk_check
     *
     * @param akskCheck the value for http_producer.aksk_check
     *
     * @mbggenerated
     */
    public void setAkskCheck(Boolean akskCheck) {
        this.akskCheck = akskCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_producer.creator
     *
     * @return the value of http_producer.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_producer.creator
     *
     * @param creator the value for http_producer.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }
}