package mystical.cup.model.database;

import java.util.Date;

public class HttpConsumerMode{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer.controller_url
     *
     * @mbggenerated
     */
    private String controllerUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer.output_param
     *
     * @mbggenerated
     */
    private String outputParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer.input_param
     *
     * @mbggenerated
     */
    private String inputParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer.ak
     *
     * @mbggenerated
     */
    private String ak;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer.sk
     *
     * @mbggenerated
     */
    private String sk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer.is_valid
     *
     * @mbggenerated
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer.decription
     *
     * @mbggenerated
     */
    private String decription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer.id
     *
     * @return the value of http_consumer.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer.id
     *
     * @param id the value for http_consumer.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer.create_time
     *
     * @return the value of http_consumer.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer.create_time
     *
     * @param createTime the value for http_consumer.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer.update_time
     *
     * @return the value of http_consumer.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer.update_time
     *
     * @param updateTime the value for http_consumer.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer.controller_url
     *
     * @return the value of http_consumer.controller_url
     *
     * @mbggenerated
     */
    public String getControllerUrl() {
        return controllerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer.controller_url
     *
     * @param controllerUrl the value for http_consumer.controller_url
     *
     * @mbggenerated
     */
    public void setControllerUrl(String controllerUrl) {
        this.controllerUrl = controllerUrl == null ? null : controllerUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer.output_param
     *
     * @return the value of http_consumer.output_param
     *
     * @mbggenerated
     */
    public String getOutputParam() {
        return outputParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer.output_param
     *
     * @param outputParam the value for http_consumer.output_param
     *
     * @mbggenerated
     */
    public void setOutputParam(String outputParam) {
        this.outputParam = outputParam == null ? null : outputParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer.input_param
     *
     * @return the value of http_consumer.input_param
     *
     * @mbggenerated
     */
    public String getInputParam() {
        return inputParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer.input_param
     *
     * @param inputParam the value for http_consumer.input_param
     *
     * @mbggenerated
     */
    public void setInputParam(String inputParam) {
        this.inputParam = inputParam == null ? null : inputParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer.ak
     *
     * @return the value of http_consumer.ak
     *
     * @mbggenerated
     */
    public String getAk() {
        return ak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer.ak
     *
     * @param ak the value for http_consumer.ak
     *
     * @mbggenerated
     */
    public void setAk(String ak) {
        this.ak = ak == null ? null : ak.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer.sk
     *
     * @return the value of http_consumer.sk
     *
     * @mbggenerated
     */
    public String getSk() {
        return sk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer.sk
     *
     * @param sk the value for http_consumer.sk
     *
     * @mbggenerated
     */
    public void setSk(String sk) {
        this.sk = sk == null ? null : sk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer.is_valid
     *
     * @return the value of http_consumer.is_valid
     *
     * @mbggenerated
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer.is_valid
     *
     * @param isValid the value for http_consumer.is_valid
     *
     * @mbggenerated
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer.type
     *
     * @return the value of http_consumer.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer.type
     *
     * @param type the value for http_consumer.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer.decription
     *
     * @return the value of http_consumer.decription
     *
     * @mbggenerated
     */
    public String getDecription() {
        return decription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer.decription
     *
     * @param decription the value for http_consumer.decription
     *
     * @mbggenerated
     */
    public void setDecription(String decription) {
        this.decription = decription == null ? null : decription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer.creator
     *
     * @return the value of http_consumer.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer.creator
     *
     * @param creator the value for http_consumer.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }
}