package mystical.cup.model.database;

import java.util.Date;

public class HttpConsumerDateMode{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer_date.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer_date.request_gid
     *
     * @mbggenerated
     */
    private String requestGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer_date.request_body
     *
     * @mbggenerated
     */
    private String requestBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer_date.response_body
     *
     * @mbggenerated
     */
    private String responseBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer_date.reques_time
     *
     * @mbggenerated
     */
    private String requesTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer_date.response_time
     *
     * @mbggenerated
     */
    private String responseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer_date.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer_date.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer_date.request_type
     *
     * @mbggenerated
     */
    private String requestType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer_date.request_url
     *
     * @mbggenerated
     */
    private String requestUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer_date.request_address
     *
     * @mbggenerated
     */
    private String requestAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column http_consumer_date.response_status
     *
     * @mbggenerated
     */
    private Integer responseStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer_date.id
     *
     * @return the value of http_consumer_date.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer_date.id
     *
     * @param id the value for http_consumer_date.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer_date.request_gid
     *
     * @return the value of http_consumer_date.request_gid
     *
     * @mbggenerated
     */
    public String getRequestGid() {
        return requestGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer_date.request_gid
     *
     * @param requestGid the value for http_consumer_date.request_gid
     *
     * @mbggenerated
     */
    public void setRequestGid(String requestGid) {
        this.requestGid = requestGid == null ? null : requestGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer_date.request_body
     *
     * @return the value of http_consumer_date.request_body
     *
     * @mbggenerated
     */
    public String getRequestBody() {
        return requestBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer_date.request_body
     *
     * @param requestBody the value for http_consumer_date.request_body
     *
     * @mbggenerated
     */
    public void setRequestBody(String requestBody) {
        this.requestBody = requestBody == null ? null : requestBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer_date.response_body
     *
     * @return the value of http_consumer_date.response_body
     *
     * @mbggenerated
     */
    public String getResponseBody() {
        return responseBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer_date.response_body
     *
     * @param responseBody the value for http_consumer_date.response_body
     *
     * @mbggenerated
     */
    public void setResponseBody(String responseBody) {
        this.responseBody = responseBody == null ? null : responseBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer_date.reques_time
     *
     * @return the value of http_consumer_date.reques_time
     *
     * @mbggenerated
     */
    public String getRequesTime() {
        return requesTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer_date.reques_time
     *
     * @param requesTime the value for http_consumer_date.reques_time
     *
     * @mbggenerated
     */
    public void setRequesTime(String requesTime) {
        this.requesTime = requesTime == null ? null : requesTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer_date.response_time
     *
     * @return the value of http_consumer_date.response_time
     *
     * @mbggenerated
     */
    public String getResponseTime() {
        return responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer_date.response_time
     *
     * @param responseTime the value for http_consumer_date.response_time
     *
     * @mbggenerated
     */
    public void setResponseTime(String responseTime) {
        this.responseTime = responseTime == null ? null : responseTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer_date.create_time
     *
     * @return the value of http_consumer_date.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer_date.create_time
     *
     * @param createTime the value for http_consumer_date.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer_date.update_time
     *
     * @return the value of http_consumer_date.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer_date.update_time
     *
     * @param updateTime the value for http_consumer_date.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer_date.request_type
     *
     * @return the value of http_consumer_date.request_type
     *
     * @mbggenerated
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer_date.request_type
     *
     * @param requestType the value for http_consumer_date.request_type
     *
     * @mbggenerated
     */
    public void setRequestType(String requestType) {
        this.requestType = requestType == null ? null : requestType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer_date.request_url
     *
     * @return the value of http_consumer_date.request_url
     *
     * @mbggenerated
     */
    public String getRequestUrl() {
        return requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer_date.request_url
     *
     * @param requestUrl the value for http_consumer_date.request_url
     *
     * @mbggenerated
     */
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl == null ? null : requestUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer_date.request_address
     *
     * @return the value of http_consumer_date.request_address
     *
     * @mbggenerated
     */
    public String getRequestAddress() {
        return requestAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer_date.request_address
     *
     * @param requestAddress the value for http_consumer_date.request_address
     *
     * @mbggenerated
     */
    public void setRequestAddress(String requestAddress) {
        this.requestAddress = requestAddress == null ? null : requestAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column http_consumer_date.response_status
     *
     * @return the value of http_consumer_date.response_status
     *
     * @mbggenerated
     */
    public Integer getResponseStatus() {
        return responseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column http_consumer_date.response_status
     *
     * @param responseStatus the value for http_consumer_date.response_status
     *
     * @mbggenerated
     */
    public void setResponseStatus(Integer responseStatus) {
        this.responseStatus = responseStatus;
    }
}