package mystical.cup.model.database;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HttpProducerModeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table http_producer
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table http_producer
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table http_producer
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer
     *
     * @mbggenerated
     */
    public HttpProducerModeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table http_producer
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table http_producer
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andReqUrlIsNull() {
            addCriterion("req_url is null");
            return (Criteria) this;
        }

        public Criteria andReqUrlIsNotNull() {
            addCriterion("req_url is not null");
            return (Criteria) this;
        }

        public Criteria andReqUrlEqualTo(String value) {
            addCriterion("req_url =", value, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlNotEqualTo(String value) {
            addCriterion("req_url <>", value, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlGreaterThan(String value) {
            addCriterion("req_url >", value, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlGreaterThanOrEqualTo(String value) {
            addCriterion("req_url >=", value, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlLessThan(String value) {
            addCriterion("req_url <", value, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlLessThanOrEqualTo(String value) {
            addCriterion("req_url <=", value, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlLike(String value) {
            addCriterion("req_url like", value, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlNotLike(String value) {
            addCriterion("req_url not like", value, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlIn(List<String> values) {
            addCriterion("req_url in", values, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlNotIn(List<String> values) {
            addCriterion("req_url not in", values, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlBetween(String value1, String value2) {
            addCriterion("req_url between", value1, value2, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlNotBetween(String value1, String value2) {
            addCriterion("req_url not between", value1, value2, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqParaConfigIsNull() {
            addCriterion("req_para_config is null");
            return (Criteria) this;
        }

        public Criteria andReqParaConfigIsNotNull() {
            addCriterion("req_para_config is not null");
            return (Criteria) this;
        }

        public Criteria andReqParaConfigEqualTo(String value) {
            addCriterion("req_para_config =", value, "reqParaConfig");
            return (Criteria) this;
        }

        public Criteria andReqParaConfigNotEqualTo(String value) {
            addCriterion("req_para_config <>", value, "reqParaConfig");
            return (Criteria) this;
        }

        public Criteria andReqParaConfigGreaterThan(String value) {
            addCriterion("req_para_config >", value, "reqParaConfig");
            return (Criteria) this;
        }

        public Criteria andReqParaConfigGreaterThanOrEqualTo(String value) {
            addCriterion("req_para_config >=", value, "reqParaConfig");
            return (Criteria) this;
        }

        public Criteria andReqParaConfigLessThan(String value) {
            addCriterion("req_para_config <", value, "reqParaConfig");
            return (Criteria) this;
        }

        public Criteria andReqParaConfigLessThanOrEqualTo(String value) {
            addCriterion("req_para_config <=", value, "reqParaConfig");
            return (Criteria) this;
        }

        public Criteria andReqParaConfigLike(String value) {
            addCriterion("req_para_config like", value, "reqParaConfig");
            return (Criteria) this;
        }

        public Criteria andReqParaConfigNotLike(String value) {
            addCriterion("req_para_config not like", value, "reqParaConfig");
            return (Criteria) this;
        }

        public Criteria andReqParaConfigIn(List<String> values) {
            addCriterion("req_para_config in", values, "reqParaConfig");
            return (Criteria) this;
        }

        public Criteria andReqParaConfigNotIn(List<String> values) {
            addCriterion("req_para_config not in", values, "reqParaConfig");
            return (Criteria) this;
        }

        public Criteria andReqParaConfigBetween(String value1, String value2) {
            addCriterion("req_para_config between", value1, value2, "reqParaConfig");
            return (Criteria) this;
        }

        public Criteria andReqParaConfigNotBetween(String value1, String value2) {
            addCriterion("req_para_config not between", value1, value2, "reqParaConfig");
            return (Criteria) this;
        }

        public Criteria andReqSuccessCodeIsNull() {
            addCriterion("req_success_code is null");
            return (Criteria) this;
        }

        public Criteria andReqSuccessCodeIsNotNull() {
            addCriterion("req_success_code is not null");
            return (Criteria) this;
        }

        public Criteria andReqSuccessCodeEqualTo(String value) {
            addCriterion("req_success_code =", value, "reqSuccessCode");
            return (Criteria) this;
        }

        public Criteria andReqSuccessCodeNotEqualTo(String value) {
            addCriterion("req_success_code <>", value, "reqSuccessCode");
            return (Criteria) this;
        }

        public Criteria andReqSuccessCodeGreaterThan(String value) {
            addCriterion("req_success_code >", value, "reqSuccessCode");
            return (Criteria) this;
        }

        public Criteria andReqSuccessCodeGreaterThanOrEqualTo(String value) {
            addCriterion("req_success_code >=", value, "reqSuccessCode");
            return (Criteria) this;
        }

        public Criteria andReqSuccessCodeLessThan(String value) {
            addCriterion("req_success_code <", value, "reqSuccessCode");
            return (Criteria) this;
        }

        public Criteria andReqSuccessCodeLessThanOrEqualTo(String value) {
            addCriterion("req_success_code <=", value, "reqSuccessCode");
            return (Criteria) this;
        }

        public Criteria andReqSuccessCodeLike(String value) {
            addCriterion("req_success_code like", value, "reqSuccessCode");
            return (Criteria) this;
        }

        public Criteria andReqSuccessCodeNotLike(String value) {
            addCriterion("req_success_code not like", value, "reqSuccessCode");
            return (Criteria) this;
        }

        public Criteria andReqSuccessCodeIn(List<String> values) {
            addCriterion("req_success_code in", values, "reqSuccessCode");
            return (Criteria) this;
        }

        public Criteria andReqSuccessCodeNotIn(List<String> values) {
            addCriterion("req_success_code not in", values, "reqSuccessCode");
            return (Criteria) this;
        }

        public Criteria andReqSuccessCodeBetween(String value1, String value2) {
            addCriterion("req_success_code between", value1, value2, "reqSuccessCode");
            return (Criteria) this;
        }

        public Criteria andReqSuccessCodeNotBetween(String value1, String value2) {
            addCriterion("req_success_code not between", value1, value2, "reqSuccessCode");
            return (Criteria) this;
        }

        public Criteria andReqTypeIsNull() {
            addCriterion("req_type is null");
            return (Criteria) this;
        }

        public Criteria andReqTypeIsNotNull() {
            addCriterion("req_type is not null");
            return (Criteria) this;
        }

        public Criteria andReqTypeEqualTo(String value) {
            addCriterion("req_type =", value, "reqType");
            return (Criteria) this;
        }

        public Criteria andReqTypeNotEqualTo(String value) {
            addCriterion("req_type <>", value, "reqType");
            return (Criteria) this;
        }

        public Criteria andReqTypeGreaterThan(String value) {
            addCriterion("req_type >", value, "reqType");
            return (Criteria) this;
        }

        public Criteria andReqTypeGreaterThanOrEqualTo(String value) {
            addCriterion("req_type >=", value, "reqType");
            return (Criteria) this;
        }

        public Criteria andReqTypeLessThan(String value) {
            addCriterion("req_type <", value, "reqType");
            return (Criteria) this;
        }

        public Criteria andReqTypeLessThanOrEqualTo(String value) {
            addCriterion("req_type <=", value, "reqType");
            return (Criteria) this;
        }

        public Criteria andReqTypeLike(String value) {
            addCriterion("req_type like", value, "reqType");
            return (Criteria) this;
        }

        public Criteria andReqTypeNotLike(String value) {
            addCriterion("req_type not like", value, "reqType");
            return (Criteria) this;
        }

        public Criteria andReqTypeIn(List<String> values) {
            addCriterion("req_type in", values, "reqType");
            return (Criteria) this;
        }

        public Criteria andReqTypeNotIn(List<String> values) {
            addCriterion("req_type not in", values, "reqType");
            return (Criteria) this;
        }

        public Criteria andReqTypeBetween(String value1, String value2) {
            addCriterion("req_type between", value1, value2, "reqType");
            return (Criteria) this;
        }

        public Criteria andReqTypeNotBetween(String value1, String value2) {
            addCriterion("req_type not between", value1, value2, "reqType");
            return (Criteria) this;
        }

        public Criteria andReqBeginTimeIsNull() {
            addCriterion("req_begin_time is null");
            return (Criteria) this;
        }

        public Criteria andReqBeginTimeIsNotNull() {
            addCriterion("req_begin_time is not null");
            return (Criteria) this;
        }

        public Criteria andReqBeginTimeEqualTo(Date value) {
            addCriterion("req_begin_time =", value, "reqBeginTime");
            return (Criteria) this;
        }

        public Criteria andReqBeginTimeNotEqualTo(Date value) {
            addCriterion("req_begin_time <>", value, "reqBeginTime");
            return (Criteria) this;
        }

        public Criteria andReqBeginTimeGreaterThan(Date value) {
            addCriterion("req_begin_time >", value, "reqBeginTime");
            return (Criteria) this;
        }

        public Criteria andReqBeginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("req_begin_time >=", value, "reqBeginTime");
            return (Criteria) this;
        }

        public Criteria andReqBeginTimeLessThan(Date value) {
            addCriterion("req_begin_time <", value, "reqBeginTime");
            return (Criteria) this;
        }

        public Criteria andReqBeginTimeLessThanOrEqualTo(Date value) {
            addCriterion("req_begin_time <=", value, "reqBeginTime");
            return (Criteria) this;
        }

        public Criteria andReqBeginTimeIn(List<Date> values) {
            addCriterion("req_begin_time in", values, "reqBeginTime");
            return (Criteria) this;
        }

        public Criteria andReqBeginTimeNotIn(List<Date> values) {
            addCriterion("req_begin_time not in", values, "reqBeginTime");
            return (Criteria) this;
        }

        public Criteria andReqBeginTimeBetween(Date value1, Date value2) {
            addCriterion("req_begin_time between", value1, value2, "reqBeginTime");
            return (Criteria) this;
        }

        public Criteria andReqBeginTimeNotBetween(Date value1, Date value2) {
            addCriterion("req_begin_time not between", value1, value2, "reqBeginTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeIsNull() {
            addCriterion("req_end_time is null");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeIsNotNull() {
            addCriterion("req_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeEqualTo(Date value) {
            addCriterion("req_end_time =", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeNotEqualTo(Date value) {
            addCriterion("req_end_time <>", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeGreaterThan(Date value) {
            addCriterion("req_end_time >", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("req_end_time >=", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeLessThan(Date value) {
            addCriterion("req_end_time <", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("req_end_time <=", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeIn(List<Date> values) {
            addCriterion("req_end_time in", values, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeNotIn(List<Date> values) {
            addCriterion("req_end_time not in", values, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeBetween(Date value1, Date value2) {
            addCriterion("req_end_time between", value1, value2, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("req_end_time not between", value1, value2, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqStepTimeIsNull() {
            addCriterion("req_step_time is null");
            return (Criteria) this;
        }

        public Criteria andReqStepTimeIsNotNull() {
            addCriterion("req_step_time is not null");
            return (Criteria) this;
        }

        public Criteria andReqStepTimeEqualTo(String value) {
            addCriterion("req_step_time =", value, "reqStepTime");
            return (Criteria) this;
        }

        public Criteria andReqStepTimeNotEqualTo(String value) {
            addCriterion("req_step_time <>", value, "reqStepTime");
            return (Criteria) this;
        }

        public Criteria andReqStepTimeGreaterThan(String value) {
            addCriterion("req_step_time >", value, "reqStepTime");
            return (Criteria) this;
        }

        public Criteria andReqStepTimeGreaterThanOrEqualTo(String value) {
            addCriterion("req_step_time >=", value, "reqStepTime");
            return (Criteria) this;
        }

        public Criteria andReqStepTimeLessThan(String value) {
            addCriterion("req_step_time <", value, "reqStepTime");
            return (Criteria) this;
        }

        public Criteria andReqStepTimeLessThanOrEqualTo(String value) {
            addCriterion("req_step_time <=", value, "reqStepTime");
            return (Criteria) this;
        }

        public Criteria andReqStepTimeLike(String value) {
            addCriterion("req_step_time like", value, "reqStepTime");
            return (Criteria) this;
        }

        public Criteria andReqStepTimeNotLike(String value) {
            addCriterion("req_step_time not like", value, "reqStepTime");
            return (Criteria) this;
        }

        public Criteria andReqStepTimeIn(List<String> values) {
            addCriterion("req_step_time in", values, "reqStepTime");
            return (Criteria) this;
        }

        public Criteria andReqStepTimeNotIn(List<String> values) {
            addCriterion("req_step_time not in", values, "reqStepTime");
            return (Criteria) this;
        }

        public Criteria andReqStepTimeBetween(String value1, String value2) {
            addCriterion("req_step_time between", value1, value2, "reqStepTime");
            return (Criteria) this;
        }

        public Criteria andReqStepTimeNotBetween(String value1, String value2) {
            addCriterion("req_step_time not between", value1, value2, "reqStepTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andStatisticsIsNull() {
            addCriterion("statistics is null");
            return (Criteria) this;
        }

        public Criteria andStatisticsIsNotNull() {
            addCriterion("statistics is not null");
            return (Criteria) this;
        }

        public Criteria andStatisticsEqualTo(Boolean value) {
            addCriterion("statistics =", value, "statistics");
            return (Criteria) this;
        }

        public Criteria andStatisticsNotEqualTo(Boolean value) {
            addCriterion("statistics <>", value, "statistics");
            return (Criteria) this;
        }

        public Criteria andStatisticsGreaterThan(Boolean value) {
            addCriterion("statistics >", value, "statistics");
            return (Criteria) this;
        }

        public Criteria andStatisticsGreaterThanOrEqualTo(Boolean value) {
            addCriterion("statistics >=", value, "statistics");
            return (Criteria) this;
        }

        public Criteria andStatisticsLessThan(Boolean value) {
            addCriterion("statistics <", value, "statistics");
            return (Criteria) this;
        }

        public Criteria andStatisticsLessThanOrEqualTo(Boolean value) {
            addCriterion("statistics <=", value, "statistics");
            return (Criteria) this;
        }

        public Criteria andStatisticsIn(List<Boolean> values) {
            addCriterion("statistics in", values, "statistics");
            return (Criteria) this;
        }

        public Criteria andStatisticsNotIn(List<Boolean> values) {
            addCriterion("statistics not in", values, "statistics");
            return (Criteria) this;
        }

        public Criteria andStatisticsBetween(Boolean value1, Boolean value2) {
            addCriterion("statistics between", value1, value2, "statistics");
            return (Criteria) this;
        }

        public Criteria andStatisticsNotBetween(Boolean value1, Boolean value2) {
            addCriterion("statistics not between", value1, value2, "statistics");
            return (Criteria) this;
        }

        public Criteria andAkIsNull() {
            addCriterion("ak is null");
            return (Criteria) this;
        }

        public Criteria andAkIsNotNull() {
            addCriterion("ak is not null");
            return (Criteria) this;
        }

        public Criteria andAkEqualTo(String value) {
            addCriterion("ak =", value, "ak");
            return (Criteria) this;
        }

        public Criteria andAkNotEqualTo(String value) {
            addCriterion("ak <>", value, "ak");
            return (Criteria) this;
        }

        public Criteria andAkGreaterThan(String value) {
            addCriterion("ak >", value, "ak");
            return (Criteria) this;
        }

        public Criteria andAkGreaterThanOrEqualTo(String value) {
            addCriterion("ak >=", value, "ak");
            return (Criteria) this;
        }

        public Criteria andAkLessThan(String value) {
            addCriterion("ak <", value, "ak");
            return (Criteria) this;
        }

        public Criteria andAkLessThanOrEqualTo(String value) {
            addCriterion("ak <=", value, "ak");
            return (Criteria) this;
        }

        public Criteria andAkLike(String value) {
            addCriterion("ak like", value, "ak");
            return (Criteria) this;
        }

        public Criteria andAkNotLike(String value) {
            addCriterion("ak not like", value, "ak");
            return (Criteria) this;
        }

        public Criteria andAkIn(List<String> values) {
            addCriterion("ak in", values, "ak");
            return (Criteria) this;
        }

        public Criteria andAkNotIn(List<String> values) {
            addCriterion("ak not in", values, "ak");
            return (Criteria) this;
        }

        public Criteria andAkBetween(String value1, String value2) {
            addCriterion("ak between", value1, value2, "ak");
            return (Criteria) this;
        }

        public Criteria andAkNotBetween(String value1, String value2) {
            addCriterion("ak not between", value1, value2, "ak");
            return (Criteria) this;
        }

        public Criteria andSkIsNull() {
            addCriterion("sk is null");
            return (Criteria) this;
        }

        public Criteria andSkIsNotNull() {
            addCriterion("sk is not null");
            return (Criteria) this;
        }

        public Criteria andSkEqualTo(String value) {
            addCriterion("sk =", value, "sk");
            return (Criteria) this;
        }

        public Criteria andSkNotEqualTo(String value) {
            addCriterion("sk <>", value, "sk");
            return (Criteria) this;
        }

        public Criteria andSkGreaterThan(String value) {
            addCriterion("sk >", value, "sk");
            return (Criteria) this;
        }

        public Criteria andSkGreaterThanOrEqualTo(String value) {
            addCriterion("sk >=", value, "sk");
            return (Criteria) this;
        }

        public Criteria andSkLessThan(String value) {
            addCriterion("sk <", value, "sk");
            return (Criteria) this;
        }

        public Criteria andSkLessThanOrEqualTo(String value) {
            addCriterion("sk <=", value, "sk");
            return (Criteria) this;
        }

        public Criteria andSkLike(String value) {
            addCriterion("sk like", value, "sk");
            return (Criteria) this;
        }

        public Criteria andSkNotLike(String value) {
            addCriterion("sk not like", value, "sk");
            return (Criteria) this;
        }

        public Criteria andSkIn(List<String> values) {
            addCriterion("sk in", values, "sk");
            return (Criteria) this;
        }

        public Criteria andSkNotIn(List<String> values) {
            addCriterion("sk not in", values, "sk");
            return (Criteria) this;
        }

        public Criteria andSkBetween(String value1, String value2) {
            addCriterion("sk between", value1, value2, "sk");
            return (Criteria) this;
        }

        public Criteria andSkNotBetween(String value1, String value2) {
            addCriterion("sk not between", value1, value2, "sk");
            return (Criteria) this;
        }

        public Criteria andAkskCheckIsNull() {
            addCriterion("aksk_check is null");
            return (Criteria) this;
        }

        public Criteria andAkskCheckIsNotNull() {
            addCriterion("aksk_check is not null");
            return (Criteria) this;
        }

        public Criteria andAkskCheckEqualTo(Boolean value) {
            addCriterion("aksk_check =", value, "akskCheck");
            return (Criteria) this;
        }

        public Criteria andAkskCheckNotEqualTo(Boolean value) {
            addCriterion("aksk_check <>", value, "akskCheck");
            return (Criteria) this;
        }

        public Criteria andAkskCheckGreaterThan(Boolean value) {
            addCriterion("aksk_check >", value, "akskCheck");
            return (Criteria) this;
        }

        public Criteria andAkskCheckGreaterThanOrEqualTo(Boolean value) {
            addCriterion("aksk_check >=", value, "akskCheck");
            return (Criteria) this;
        }

        public Criteria andAkskCheckLessThan(Boolean value) {
            addCriterion("aksk_check <", value, "akskCheck");
            return (Criteria) this;
        }

        public Criteria andAkskCheckLessThanOrEqualTo(Boolean value) {
            addCriterion("aksk_check <=", value, "akskCheck");
            return (Criteria) this;
        }

        public Criteria andAkskCheckIn(List<Boolean> values) {
            addCriterion("aksk_check in", values, "akskCheck");
            return (Criteria) this;
        }

        public Criteria andAkskCheckNotIn(List<Boolean> values) {
            addCriterion("aksk_check not in", values, "akskCheck");
            return (Criteria) this;
        }

        public Criteria andAkskCheckBetween(Boolean value1, Boolean value2) {
            addCriterion("aksk_check between", value1, value2, "akskCheck");
            return (Criteria) this;
        }

        public Criteria andAkskCheckNotBetween(Boolean value1, Boolean value2) {
            addCriterion("aksk_check not between", value1, value2, "akskCheck");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table http_producer
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table http_producer
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}