package mystical.cup.model.database;

import java.util.Date;

public class RequestJob {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_job.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_job.req_url
     *
     * @mbggenerated
     */
    private String reqUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_job.req_para_config
     *
     * @mbggenerated
     */
    private String reqParaConfig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_job.req_success_code
     *
     * @mbggenerated
     */
    private String reqSuccessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_job.req_type
     *
     * @mbggenerated
     */
    private String reqType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_job.req_begin_time
     *
     * @mbggenerated
     */
    private String reqBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_job.req_end_time
     *
     * @mbggenerated
     */
    private String reqEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_job.req_step_time
     *
     * @mbggenerated
     */
    private String reqStepTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_job.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_job.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_job.statistics
     *
     * @mbggenerated
     */
    private Boolean statistics;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_job.id
     *
     * @return the value of request_job.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_job.id
     *
     * @param id the value for request_job.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_job.req_url
     *
     * @return the value of request_job.req_url
     *
     * @mbggenerated
     */
    public String getReqUrl() {
        return reqUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_job.req_url
     *
     * @param reqUrl the value for request_job.req_url
     *
     * @mbggenerated
     */
    public void setReqUrl(String reqUrl) {
        this.reqUrl = reqUrl == null ? null : reqUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_job.req_para_config
     *
     * @return the value of request_job.req_para_config
     *
     * @mbggenerated
     */
    public String getReqParaConfig() {
        return reqParaConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_job.req_para_config
     *
     * @param reqParaConfig the value for request_job.req_para_config
     *
     * @mbggenerated
     */
    public void setReqParaConfig(String reqParaConfig) {
        this.reqParaConfig = reqParaConfig == null ? null : reqParaConfig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_job.req_success_code
     *
     * @return the value of request_job.req_success_code
     *
     * @mbggenerated
     */
    public String getReqSuccessCode() {
        return reqSuccessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_job.req_success_code
     *
     * @param reqSuccessCode the value for request_job.req_success_code
     *
     * @mbggenerated
     */
    public void setReqSuccessCode(String reqSuccessCode) {
        this.reqSuccessCode = reqSuccessCode == null ? null : reqSuccessCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_job.req_type
     *
     * @return the value of request_job.req_type
     *
     * @mbggenerated
     */
    public String getReqType() {
        return reqType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_job.req_type
     *
     * @param reqType the value for request_job.req_type
     *
     * @mbggenerated
     */
    public void setReqType(String reqType) {
        this.reqType = reqType == null ? null : reqType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_job.req_begin_time
     *
     * @return the value of request_job.req_begin_time
     *
     * @mbggenerated
     */
    public String getReqBeginTime() {
        return reqBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_job.req_begin_time
     *
     * @param reqBeginTime the value for request_job.req_begin_time
     *
     * @mbggenerated
     */
    public void setReqBeginTime(String reqBeginTime) {
        this.reqBeginTime = reqBeginTime == null ? null : reqBeginTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_job.req_end_time
     *
     * @return the value of request_job.req_end_time
     *
     * @mbggenerated
     */
    public String getReqEndTime() {
        return reqEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_job.req_end_time
     *
     * @param reqEndTime the value for request_job.req_end_time
     *
     * @mbggenerated
     */
    public void setReqEndTime(String reqEndTime) {
        this.reqEndTime = reqEndTime == null ? null : reqEndTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_job.req_step_time
     *
     * @return the value of request_job.req_step_time
     *
     * @mbggenerated
     */
    public String getReqStepTime() {
        return reqStepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_job.req_step_time
     *
     * @param reqStepTime the value for request_job.req_step_time
     *
     * @mbggenerated
     */
    public void setReqStepTime(String reqStepTime) {
        this.reqStepTime = reqStepTime == null ? null : reqStepTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_job.create_time
     *
     * @return the value of request_job.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_job.create_time
     *
     * @param createTime the value for request_job.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_job.update_time
     *
     * @return the value of request_job.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_job.update_time
     *
     * @param updateTime the value for request_job.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_job.statistics
     *
     * @return the value of request_job.statistics
     *
     * @mbggenerated
     */
    public Boolean getStatistics() {
        return statistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_job.statistics
     *
     * @param statistics the value for request_job.statistics
     *
     * @mbggenerated
     */
    public void setStatistics(Boolean statistics) {
        this.statistics = statistics;
    }
}